### PR TITLE
adapter.process() Causes Error: Cannot set headers after they are sent to the client

### LINKED ISSUE #1005: adapter.process() Causes Error: Cannot set headers after they are sent to the client
**Version**
1.3.1

**Describe the bug**
When using adapter.process(req, res, logic) and the end() closure is called with `isInvokeResponseOrExpectReplies=true`, it calls res.setHeader() after the bot logic completes:
Image

If the logic callback ends the response early (e.g., res.status(200).end() to flush a 200 before a long-running operation and avoid channel timeouts), the subsequent res.setHeader() call in end() throws:
```Error: Cannot set headers after they are sent to the client```
This was not an issue with the BotBuilder SDK, which did not call setHeader in the equivalent code path.

**To Reproduce**
1. Call adapter.process(req, res, logic)
2. Inside logic, call res.status(200).end() to send the response early
3. The adapter's end() closure runs after logic completes and throws the error.

**Expected behavior**
adapter.process() should not throw if the response has already been sent by user code within the logic callback.

**Suggested Fix**
Add a res.headersSent guard in the end() closure:
```
const end = (status: StatusCodes, body?: unknown, isInvokeResponseOrExpectReplies: boolean = false) => {
    if (res.headersSent) {
        return
    }
    res.status(status)
    if (isInvokeResponseOrExpectReplies) {
        res.setHeader('content-type', 'application/json')
    }
    if (body) {
        res.send(body)
    }
    res.end()
}
```

### PR DESCRIPTION
**Pull request by sw-joelmut**
Fixes #1005

This pull request improves the robustness of the `CloudAdapter` response handling and adds corresponding test coverage. The main focus is to ensure that the adapter does not attempt to modify the HTTP response if it has already been committed, preventing potential errors and unexpected behavior.

Key changes:

**CloudAdapter response handling:**
* Updated the `end` function in `CloudAdapter` to check `res.headersSent` and `res.writableEnded` before attempting to modify the response, ensuring no further actions are taken if the response has already been sent.

**Test enhancements:**
* Added `headersSent` and `writableEnded` properties to the mock `res` object in the CloudAdapter tests to support the new logic.
* Introduced a new test case to verify that the adapter does not attempt to modify the response if it has already been committed, ensuring the new guard clause works as intended.

**Testing**
The following image shows the sample working.
image

### CODE REVIEW

File: packages/agents-hosting/src/cloudAdapter.ts [hunk 1]
```diff
@@ -336,6 +336,14 @@ export class CloudAdapter extends BaseAdapter {
     }
 
     const end = (status: StatusCodes, body?: unknown, isInvokeResponseOrExpectReplies: boolean = false) => {
+      if (res.writableEnded) {
+        return
+      }
+
+      if (res.headersSent) {
+        res.end()
```
Comment (benbrown) [inline packages/agents-hosting/src/cloudAdapter.ts:344]: this discards the body if present. intentional? Probably?

**Review by benbrown — APPROVED** [review]
