### PR TITLE
[#299] ServiceURl Should not be required when DeliveryMode = ExpectReplies

### LINKED ISSUE #299: ServiceURl Should not be required when DeliveryMode = ExpectReplies
**Describe the bug**
When sending an activity with ExpectReplies in the delivery mode property. ServiceURL should not be required. 

**To Reproduce**
Send an activity with deliveryMode = ExpectReplies without populating the Service URL
an exception is raised indicating that the ServiceUrl is required. 

**Expected behavior**
Send an activity with deliveryMode = ExpectReplie without populating the Service URL
Request should be honored without error

### PR DESCRIPTION
**Pull request by ceciliaavila**
Fixes #299

## Description
This PR ports the changes from .NET [PR#270](https://github.com/microsoft/Agents-for-net/pull/270) to evaluate the necessity of creating a client connector depending on the activity's delivery mode and the service URL.

## Detailed Changes
- Removed `serviceURL` validation in `Activity` class.
- Added new `resolveIfConnectorClientIsNeeded` method and called it before creating the _connectorClient_ instance in `CloudAdapter's process`.
- Removed unit test validating the ServiceUrl is defined in the activity.

### Additional Changes
- Added `expectReplies` sample to show how expectReplies activities are handled.
- Added unit tests in `CloudAdapter.tests` to cover the different activity types handled by the _process_ method.
## Testing
The root-agent sample is currently not working on expectReplies mode. We tested the changes using two unit tests that weren't included in this PR.
image

### CODE REVIEW

**Review by rido-min — COMMENTED** [review]
can you add a test under `samples/` to showcase how an activity with Expect Replies is handled?

I think this is a good time to revisit 

https://github.com/microsoft/Agents-for-js/blob/c56dea92f8a49accc8477734395a92fb767253f9/packages/agents-hosting/src/cloudAdapter.ts#L207-L221

including the CloudAdapter unitests 

Also, make sure we cover invoke Activities.

File: samples/basic/expectReplies.ts [hunk 1]
```diff
@@ -0,0 +1,52 @@
+import { startServer } from '@microsoft/agents-hosting-express'
+import { AgentApplication, CloudAdapter, loadAuthConfigFromEnv, MemoryStorage, TurnContext, TurnState } from '@microsoft/agents-hosting'
+import { DeliveryModes } from '@microsoft/agents-activity'
+
+const adapter = new CloudAdapter(loadAuthConfigFromEnv())
+// Patch process to log the invokeResponse sent to the client
+const originalProcess = adapter.process.bind(adapter)
+adapter.process = async (req, res, logic) => {
```
Comment (rido-min) [inline samples/basic/expectReplies.ts:8]: not sure I follow.. Why we need to override process?

Comment (ceciliaavila) [reply samples/basic/expectReplies.ts:8]: We added a binding for the process to be able to log the invoke response, evidencing that the activities are included in it. This is the only method we found as the response is returned after all handlers are executed.

Comment (rido-min) [reply samples/basic/expectReplies.ts:8]: we can log from the adapter.. no? 

One way to test this is to sending a request and assert the response

**Review by rido-min — APPROVED** [review]
