### PR TITLE
Fix/usertokenclient refreshtoken

### LINKED ISSUE #459: UserTokenService does not refresh tokens
```
2025-07-15T20:42:48.6027921Z stderr F 2025-07-15T20:42:48.602Z agents:user-token-client:error AxiosError: Request failed with status code 401
2025-07-15T20:42:48.6028445Z stderr F     at settle (/app/bundle.cjs:73559:16)
2025-07-15T20:42:48.6028648Z stderr F     at IncomingMessage.handleStreamEnd (/app/bundle.cjs:74396:15)
2025-07-15T20:42:48.6028665Z stderr F     at IncomingMessage.emit (node:events:519:35)
2025-07-15T20:42:48.6028676Z stderr F     at endReadableNT (node:internal/streams/readable:1701:12)
2025-07-15T20:42:48.6028685Z stderr F     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
2025-07-15T20:42:48.6028694Z stderr F     at Axios.request (/app/bundle.cjs:75202:45)
2025-07-15T20:42:48.6028705Z stderr F     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-07-15T20:42:48.6028715Z stderr F     at async UserTokenClient.getUserToken (/app/bundle.cjs:75720:28)
2025-07-15T20:42:48.6028724Z stderr F     at async OAuthFlow.getUserToken (/app/bundle.cjs:75897:31)
2025-07-15T20:42:48.6028733Z stderr F     at async Authorization.beginOrContinueFlow (/app/bundle.cjs:76379:25)
2025-07-15T20:42:48.6028741Z stderr F     at async /app/bundle.cjs:77632:39
2025-07-15T20:42:48.6028750Z stderr F     at async AutoSignInDemo.runInternal (/app/bundle.cjs:77611:16)
2025-07-15T20:42:48.6028767Z stderr F     at async AutoSignInDemo.run (/app/bundle.cjs:77577:9)
2025-07-15T20:42:48.6028777Z stderr F     at async /app/bundle.cjs:80115:65
2025-07-15T20:42:48.6028785Z stderr F     at async MiddlewareSet.run (/app/bundle.cjs:80031:16)
2025-07-15T20:42:48.6081342Z stderr F 2025-07-15T20:42:48.608Z agents:oauth-flow:warn Flow expired
```

### PR DESCRIPTION
**Pull request by rido-min**
fixes #459 and #263 

This pull request introduces significant changes to the `agents-hosting` package, focusing on enhancing token management, improving the `CloudAdapter` and `OAuthFlow` classes, and simplifying error handling within the `UserTokenClient`. The most important updates involve replacing the `BaseAdapter` with `CloudAdapter`, improving token refresh logic, and streamlining error handling in the `UserTokenClient`.

### Token Management Enhancements:
* [`packages/agents-hosting/src/oauth/oAuthFlow.ts`](diffhunk://#diff-7d4f8b1892c4612c4724dc05cc69e1dad66f8e2034b4b4863aeb16a97fa0cc8fL335-R347): Replaced the `initializeTokenClient` method with `refreshToken`, adding token caching and automatic refresh logic using `jwt`. This ensures that tokens are kept up-to-date and reduces redundant initialization. [[1]](diffhunk://#diff-7d4f8b1892c4612c4724dc05cc69e1dad66f8e2034b4b4863aeb16a97fa0cc8fL335-R347) [[2]](diffhunk://#diff-7d4f8b1892c4612c4724dc05cc69e1dad66f8e2034b4b4863aeb16a97fa0cc8fR122)

### Adapter Improvements:
* [`packages/agents-hosting/src/app/agentApplication.ts`](diffhunk://#diff-eb62ee565800a96a056213566c64b9dba3ab20f387cef5c8dc2facf8845507d2L74-R75): Replaced the `BaseAdapter` with `CloudAdapter` and added fallback logic to initialize a new `CloudAdapter` when no adapter is provided. [[1]](diffhunk://#diff-eb62ee565800a96a056213566c64b9dba3ab20f387cef5c8dc2facf8845507d2L74-R75) [[2]](diffhunk://#diff-eb62ee565800a96a056213566c64b9dba3ab20f387cef5c8dc2facf8845507d2R122-R127)
* [`packages/agents-hosting/src/cloudAdapter.ts`](diffhunk://#diff-0c14fd717680b2a2fcf5072417547179c0964b6f49aa89b7bf8717268fb0f420L47-R52): Updated the `CloudAdapter` constructor to support optional parameters for `AuthConfiguration`, `AuthProvider`, and `UserTokenClient`, enabling more flexible initialization.

### Error Handling Simplification:
* [`packages/agents-hosting/src/oauth/userTokenClient.ts`](diffhunk://#diff-394ddc5894236f1228ead6d2141128a24f9d83477dd2e2908f56149e63c3f787L34-R60): Removed redundant try-catch blocks in methods like `getUserToken`, `signOut`, and `getSignInResource`. Added response interceptors for improved logging and error handling. [[1]](diffhunk://#diff-394ddc5894236f1228ead6d2141128a24f9d83477dd2e2908f56149e63c3f787L34-R60) [[2]](diffhunk://#diff-394ddc5894236f1228ead6d2141128a24f9d83477dd2e2908f56149e63c3f787L47-L57) [[3]](diffhunk://#diff-394ddc5894236f1228ead6d2141128a24f9d83477dd2e2908f56149e63c3f787L87)

### Authorization Enhancements:
* [`packages/agents-hosting/src/app/authorization.ts`](diffhunk://#diff-761a83b5828fc696042d8f17f11915a24566fb71a63bc212fd2a8b1e0e70fd7cL119-R119): Updated the `Authorization` class to use `UserTokenClient` for token management, ensuring tighter integration with the new token handling logic. [[1]](diffhunk://#diff-761a83b5828fc696042d8f17f11915a24566fb71a63bc212fd2a8b1e0e70fd7cL119-R119) [[2]](diffhunk://#diff-761a83b5828fc696042d8f17f11915a24566fb71a63bc212fd2a8b1e0e70fd7cL136-R136)

### Miscellaneous Updates:
* [`packages/agents-hosting/src/oauth/index.ts`](diffhunk://#diff-45c456de2b4953ad3ed3d0a3e6692c587e99d1c6642c8bf8dd6a10f9a24e100fR3): Fixed duplicate export of `userTokenClient`.

### CODE REVIEW

File: packages/agents-hosting-express/src/startServer.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export const startServer = (agent: AgentApplication<TurnState<any, any>> | Activ
   const authConfig: AuthConfiguration = authConfiguration ?? loadAuthConfigFromEnv()
   let adapter: CloudAdapter
   if (agent instanceof ActivityHandler || !agent.adapter) {
-    adapter = new CloudAdapter(authConfig)
+    adapter = new CloudAdapter()
```
Comment (rido-min) [inline packages/agents-hosting-express/src/startServer.ts:40]: if not config is passed, it will use the default config

File: packages/agents-hosting/src/oauth/userTokenClient.ts [hunk 2]
```diff
@@ -15,14 +15,12 @@ const logger = debug('agents:user-token-client')
...
   client: AxiosInstance
-  msAppId: string
   /**
    * Creates a new instance of UserTokenClient.
    * @param token The token to use for authentication.
    * @param msAppId The Microsoft application ID.
    */
-  constructor (token: string, appId: string) {
-    this.msAppId = appId
+  constructor (private msAppId: string) {
```
Comment (rido-min) [inline packages/agents-hosting/src/oauth/userTokenClient.ts:23]: token out of the ctor, so the caller needs to set it before invoking any method.
