### PR TITLE
[#384] Fix FIC authentication for Agentic scenarios

### LINKED ISSUE #834: Fix FIC authentication for Agentic scenarios
## Description

When using Agentic + FIC, customers have this error:

``` txt
2025-12-09T07:47:32.0512669Z     },
2025-12-09T07:47:32.0512689Z     data: {
2025-12-09T07:47:32.0512709Z       error: 'invalid_client',
2025-12-09T07:47:32.051274Z       error_description: "AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type. Trace ID: 69896b63-9e24-4bf6-9767-f762c1154f00 Correlation ID: af3c7a8e-eb33-40bd-a82a-7c6139e3b5f8 Timestamp: 2025-12-09 07:47:31Z",
2025-12-09T07:47:32.0512761Z       error_codes: [ 7000216 ],
2025-12-09T07:47:32.0512781Z       timestamp: '2025-12-09 07:47:31Z',
2025-12-09T07:47:32.0512803Z       trace_id: '69896b63-9e24-4bf6-9767-f762c1154f00',
2025-12-09T07:47:32.0512824Z       correlation_id: 'af3c7a8e-eb33-40bd-a82a-7c6139e3b5f8',
2025-12-09T07:47:32.0512866Z       error_uri: 'https://login.microsoftonline.com/error?code=7000216'
2025-12-09T07:47:32.0512886Z     }
2025-12-09T07:47:32.0512905Z   },
2025-12-09T07:47:32.0512924Z   status: 401
2025-12-09T07:47:32.0512943Z }
2025-12-09T07:47:32.0512962Z
2025-12-09T07:47:32.0512982Z Node.js v20.19.5
```

We need to update `getAgenticApplicationToken` to do the same thing as for non-agentic, except with the _fmi_path_ and proper _scope_.

### PR DESCRIPTION
**Pull request by ceciliaavila**
Fixes #834

## Description

This PR updates the `getAgenticApplicationToken` in _MsalTokenProvider_ to support other authentication types (FIC, certificates, and Workload Identity) besides clientSecret.
Additionally, it adds the new `sendX5C` setting to _AuthConfiguration_ to distinguish between certificates and SNI authentication.

## Testing
We don't have the necessary permissions to test the Agentic route. This will be tested by the A365 team.

### CODE REVIEW

**Review by benbrown — DISMISSED** [review]

File: packages/agents-hosting/src/auth/authConfiguration.ts [hunk 1]
```diff
@@ -218,16 +225,23 @@ function loadConnectionsMapFromEnv () {
...
+  for (const [key, rawValue] of Object.entries(envVars)) {
     if (key.startsWith(CONNECTIONS_PREFIX)) {
       // Convert to dot notation
       let path = key.substring(CONNECTIONS_PREFIX.length).replace(/__/g, '.')
       // Remove ".settings." from the path
       path = path.replace('.settings.', '.')
+      // Convert "true"/"false" strings into boolean values
+      let value
+      if (rawValue === 'true' || rawValue === 'false') {
+        value = rawValue === 'true'
```
Comment (benbrown) [inline packages/agents-hosting/src/auth/authConfiguration.ts]: this took me 3 reads to understand.
